spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoes_shop?useSSL=false&allowPublicKeyRetrieval=true
    username: Aishwarya
    password: appagang2359@##

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 4000